# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.15
      
    working_directory: ~/pyaci

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m virtualenv venv
            . venv/bin/activate
            pip install -e .[doc,test]

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir ~/.aci-meta
            cp meta/aci-meta.limited.json ~/.aci-meta/aci-meta.json
            nosetests --with-coverage --cover-html --cover-package=pyaci

      - store_artifacts:
          path: cover
          destination: cover
